version: '3.1'

services:
  boxdb:
    user: "nfsnobody"
    image: mongo:7.0.6
    container_name: ${MONGO_DB_NAME}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./mongo:/data/db
