version: '3.1'

services:
  boxdb:
    image: mongo:7.0.6
    container_name: boxdb
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_DATABASE: boxdb
    volumes:
      - ./mongo:/data/db
