version: '3.1'

services:
  boxdb:
    image: mongo:7.0.7
    container_name: ${MONGO_DB_NAME}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      TZ: ${TIME_ZONE}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./mongo:/data/db
